services:

  core-frontend:
    image: rer-frontend:latest
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - GITLAB_TOKEN=${GITLAB_TOKEN}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=
        - APP_VERSION=${APP_VERSION}
    container_name: core-frontend
    restart: unless-stopped
    networks:
      # - frontend_network
      - gateway_network