version: '3'
services:

  front:
    # image: vuejscardpgfrontend:0.0.1
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - GITLAB_TOKEN=${GITLAB_TOKEN}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - APP_VERSION=${APP_VERSION}
    container_name: vuejs-car-dpg-frontend
    ports:
      - "5000:80"
    restart: unless-stopped
